//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Areas_Admin_Views_AdminSchools_AddClass_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Admin_Views_AdminSchools_AddClass_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SchoolManagementSystem.Web.Resources.Areas_Admin_Views_AdminSchools_AddClass_en", typeof(Areas_Admin_Views_AdminSchools_AddClass_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        internal static string ClassNameText {
            get {
                return ResourceManager.GetString("ClassNameText", resourceCulture);
            }
        }
        
        internal static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        internal static string SelectSpeciality {
            get {
                return ResourceManager.GetString("SelectSpeciality", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
    }
}
