//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Areas_Admin_Views_Admin_Dashboard_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Areas_Admin_Views_Admin_Dashboard_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SchoolManagementSystem.Web.Resources.Areas_Admin_Views_Admin_Dashboard_en", typeof(Areas_Admin_Views_Admin_Dashboard_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string ManageStudents {
            get {
                return ResourceManager.GetString("ManageStudents", resourceCulture);
            }
        }
        
        internal static string ManageStudentsText {
            get {
                return ResourceManager.GetString("ManageStudentsText", resourceCulture);
            }
        }
        
        internal static string ManageTeachers {
            get {
                return ResourceManager.GetString("ManageTeachers", resourceCulture);
            }
        }
        
        internal static string ManageTeachersText {
            get {
                return ResourceManager.GetString("ManageTeachersText", resourceCulture);
            }
        }
        
        internal static string ManageSchools {
            get {
                return ResourceManager.GetString("ManageSchools", resourceCulture);
            }
        }
        
        internal static string ManageSchoolsText {
            get {
                return ResourceManager.GetString("ManageSchoolsText", resourceCulture);
            }
        }
        
        internal static string ManageProjects {
            get {
                return ResourceManager.GetString("ManageProjects", resourceCulture);
            }
        }
        
        internal static string ManageProjectsText {
            get {
                return ResourceManager.GetString("ManageProjectsText", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
